# DATA SCIENCE

## python basics

In [1]:
2+2 #

4

In [2]:
3/2 #this will give us a floatin point datatype

1.5

In [5]:
type(2) #this will give the datatype of the value

int

In [7]:
str='hello world'
print(str)

hello world


In [8]:
str #there will be output because of the jupyter notebook feature along with the quotes

'hello world'

In [9]:
'{} is the most played sport in the {}'.format('football','earth')

'football is the most played sport in the earth'

In [10]:
'{one} is the most played sport in the {two}, and {one} is my favourite sport'.format(one='football',two='earth')

'football is the most played sport in the earth, and football is my favourite sport'

In [11]:
lst=[1,2,3,2,1,3] #list is enclosed with square brackets

In [12]:
lst[1:3] #slicing, we can also access individual elements the usual way

[2, 3]

In [14]:
lst=[1,2,[3,4,[5,5]]] #lists can be nested also
print(lst)

[1, 2, [3, 4, [5, 5]]]


In [24]:
dic={'k1':'hello','k2':'world','k3':'this is nitin'} #this is dict which stores key-value pair
dic

{'k1': 'hello', 'k2': 'world', 'k3': 'this is nitin'}

In [25]:
for key in dic:
    print(dic[key])

hello
world
this is nitin


In [26]:
tup=(2,3,5,1,4) #tuples are immutable list which are enclosed within circular brackets

In [27]:
tup[0]=0

TypeError: 'tuple' object does not support item assignment

In [31]:
lst.append(7) #we can add element at the end in list but not in tuple

In [35]:
eset={4,4,3,4,5,5,3,1,1} #set only stores unique values and in order

In [37]:
eset.add(7) #we can add value using add method
eset

{1, 3, 4, 5, 7}

In [38]:
True and (False or False) #boolean values and operations

False

In [39]:
if 5>4:            #if-else also there is if-elif-else
    print('yello')
else:
    print('mello')

yello


In [40]:
for element in lst: #goes through each value in list
    print(element)

1
2
[3, 4, [5, 5]]
7


In [42]:
list(range(0,4,1))

[0, 1, 2, 3]

In [43]:
for i in range(4): #range function makes range using the value provided
    print(i)

0
1
2
3


In [44]:
#we can do for loop operation inside a list also, like
a=[num*2 for num in lst]
a

[2, 4, [3, 4, [5, 5], 3, 4, [5, 5]], 14]

In [49]:
#we can make user-defined functions like:
def func(str='momo'):
    return('hello '+str)
func('nitin')

'hello nitin'

In [50]:
list(map(func,['nitin','rohit','messi'])) #map applies the operation to all the elements in the list

['hello nitin', 'hello rohit', 'hello messi']

In [51]:
#similar to this we have filter function, which can remove elements according to the condition
list(filter(lambda num:num%2, [2,3,25,5,7,4])) #lambda function is a concise way of writint functions

[3, 25, 5, 7]

In [52]:
'hello world! This is Nitin Rohit'.split() #splits the string according to the delimiter

['hello', 'world!', 'This', 'is', 'Nitin', 'Rohit']

In [53]:
'Nitin' in 'hello world! This is Nitin Rohit' #in finds the presence of the value in the given list

True

## NumPy Basics

In [54]:
#importing the numpy module
import numpy as np

In [55]:
#making list from previous value
lst=[3,4,2,1]
nplist=np.array(lst)
nplist

array([3, 4, 2, 1])

In [56]:
np.arange(0,11,2) #works like range function in normal python

array([ 0,  2,  4,  6,  8, 10])

In [57]:
np.ones(4) #gives array with all values with one

array([1., 1., 1., 1.])

In [58]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
np.zeros(3) #gives array with all values with zero

array([0., 0., 0.])

In [60]:
np.eye(4) #gives an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
np.linspace(1,10,19) #gives linearly spaced values 

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [66]:
np.random.rand(4) #this will give array with random values between 0-1

array([0.85035787, 0.83862407, 0.68458146, 0.39346086])

In [68]:
np.random.rand(4,4)

array([[0.42313464, 0.06766171, 0.63628588, 0.21502561],
       [0.8317487 , 0.64257026, 0.38016398, 0.59220154],
       [0.79200641, 0.36082346, 0.05824756, 0.55320786],
       [0.50095363, 0.05487977, 0.37710268, 0.94778808]])

In [69]:
np.random.randn(4) #this is same as rand but will give normal distribution

array([-0.92474896, -1.79503006,  0.33916856, -0.15911912])

In [70]:
np.random.randint(0,10,10) #will give integer random numbers

array([1, 8, 2, 9, 6, 9, 6, 0, 3, 4])

In [72]:
nplist[1:3] #slicing

array([4, 2])

In [73]:
nplist[1:3]=100 #broadcasting, this will set the values of all the values in the slice range
nplist

array([  3, 100, 100,   1])

In [74]:
temp=nplist[1:3]
temp[:]=200
temp

array([200, 200])

In [75]:
nplist #the actual array also changes as no new copy is created during slicing unlike normal python

array([  3, 200, 200,   1])

In [76]:
nplist=np.arange(1,21).reshape(5,4)
nplist

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [78]:
nplist[1:3,1:3] #2D slicing, broadcasting can also be done with this

array([[ 6,  7],
       [10, 11]])

In [81]:
nplist[nplist>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [84]:
nplist**2 #operation happens to all the elements in the array

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256],
       [289, 324, 361, 400]])

In [88]:
nplist.min()

1

## Pandas basics


In [91]:
#importing pandas
import pandas as pd
#Series Datatype
s=pd.Series([23,19,22]) #we can also pass index value with an array
s

0    23
1    19
2    22
dtype: int64

In [93]:
s[s>20]

0    23
2    22
dtype: int64

In [98]:
#we can also pass dict to the series datatype
table={'k1':'name1','k2':'name2','k3':'name3'}
s1=pd.Series(table)
s1

k1    name1
k2    name2
k3    name3
dtype: object

In [99]:
table={'k1':'name1','k2':'name2','k4':'name4'}
s2=pd.Series(table)
s1+s2

k1    name1name1
k2    name2name2
k3           NaN
k4           NaN
dtype: object

In [104]:
#DataFrame
temp=np.arange(0,20).reshape(4,5)
ind='a b c d'.split()
head='v w x y z'.split()
df=pd.DataFrame(temp,ind,head)
df

v   w   x   y   z
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19

In [105]:
#we can get a particular column which will be in the form of series datatype
df['x']

a     2
b     7
c    12
d    17
Name: x, dtype: int64

In [106]:
#we can also get mulitple cols at the same time
df[['x','z']]

x   z
a   2   4
b   7   9
c  12  14
d  17  19

In [107]:
#we can create new col by following
df['x-z sum']=df['x']+df['z']
df

v   w   x   y   z  x-z sum
a   0   1   2   3   4        6
b   5   6   7   8   9       16
c  10  11  12  13  14       26
d  15  16  17  18  19       36

In [108]:
#we can remove a particular column using the drop method
df.drop('x-z sum',axis=1)

v   w   x   y   z
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19

In [113]:
#we can access the row of the table using loc method
df.loc['b']

v           5
w           6
x           7
y           8
z           9
x-z sum    16
Name: b, dtype: int64

In [114]:
#can also get multiple rows
df.loc[['b','d']]

v   w   x   y   z  x-z sum
b   5   6   7   8   9       16
d  15  16  17  18  19       36

In [115]:
#we can perform bool operation on the table
df[(df>10)]

v     w     x     y     z  x-z sum
a   NaN   NaN   NaN   NaN   NaN      NaN
b   NaN   NaN   NaN   NaN   NaN     16.0
c   NaN  11.0  12.0  13.0  14.0     26.0
d  15.0  16.0  17.0  18.0  19.0     36.0

In [116]:
df[df['z']>10] #for row it will remove the entire row which doesn't follow the condition

v   w   x   y   z  x-z sum
c  10  11  12  13  14       26
d  15  16  17  18  19       36

In [123]:
new=pd.DataFrame({'a':[1,2,np.nan],'b':[np.nan,2,np.nan],'c':[1,np.nan,3]})

In [124]:
new

a    b    c
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  NaN  3.0

In [133]:
new.dropna(thresh=1)

a    b    c
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  NaN  3.0

In [152]:
comdata=pd.DataFrame({'company':['goog','goog','ama','face','face','face'],'sal':[10,9,8,8,7,9]})

In [153]:
comdata

company  sal
0    goog   10
1    goog    9
2     ama    8
3    face    8
4    face    7
5    face    9

In [160]:
comdata.groupby('company').describe().transpose()

company    ama  face       goog
sal count  1.0   3.0   2.000000
    mean   8.0   8.0   9.500000
    std    NaN   1.0   0.707107
    min    8.0   7.0   9.000000
    25%    8.0   7.5   9.250000
    50%    8.0   8.0   9.500000
    75%    8.0   8.5   9.750000
    max    8.0   9.0  10.000000